import {library} from '@fortawesome/fontawesome-svg-core'
import {
    faBars,
    faCalendar,
    faChevronLeft,
    faChevronRight,
    faCogs,
    faEdit,
    faEuroSign,
    faFile,
    faFolder,
    faFont,
    faHome,
    faImages,
    faPaperPlane,
    faPhotoVideo,
    faSignOutAlt,
    faTrashAlt,
    faTrophy,
    faUser,
    faPencil,
    faUserSecret,
    faArrowUp,
    faArrowDown,
    faClone,
    faTrash,
    faArrowsUpDownLeftRight,
    faCode,
    faPlus,
    faEllipsis,
    faGrip,
    faMobile,
    faTablet,
    faDisplay, faColumns, faTableCells, faTableColumns, faCubes, faCube, faPaintbrush, faUndo, faRedo
} from '@fortawesome/free-solid-svg-icons'
import {faInstagram, faTwitter} from '@fortawesome/free-brands-svg-icons'
import {FontAwesomeIcon} from '@fortawesome/vue-fontawesome'

library.add(
    faHome,
    faTwitter,
    faInstagram,
    faChevronLeft,
    faChevronRight,
    faBars,
    faUser,
    faHome,
    faFont,
    faPhotoVideo,
    faPaperPlane,
    faEuroSign,
    faTrophy,
    faCalendar,
    faImages,
    faCogs,
    faSignOutAlt,
    faEdit,
    faTrashAlt,
    faFolder,
    faFile,
    faPencil,
    faUserSecret,
    faArrowUp,
    faArrowDown,
    faClone,
    faTrash,
    faArrowsUpDownLeftRight,
    faCode,
    faPlus,
    faEllipsis,
    faGrip,
    faMobile,
    faTablet,
    faDisplay,
    faColumns,
    faTableCells,
    faTableColumns,
    faCubes,
    faCube,
    faPaintbrush,
    faUndo,
    faRedo
)

export {FontAwesomeIcon}
